config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "has already been bookmarked for this list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:destroy]

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list_id = @list.id

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
  end

  def show
    @review = Review.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # We need to find the List associated with the review
  before_action :set_list, only: %i[new create]

  def create
    @review = Review.new(review_params)
    @review.list = @list
    @review.save
    redirect_to list_path(@list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def review_params
    params.require(:review).permit(:content, :stars)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_forms.html.erb
<%= render "components/banner", text: "", title: "Add your movie" %>

<div class="container">

  <div class="d-flex justify-content-center mt-5 ">
    <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.input :comment %>
        <%= f.association :movie %>
      <%=  f.button :submit, class: "btn btn-lg mt-5 backgradient" %>
    <% end %>
  </div>
</div>

app/views/bookmarks/new.html.erb
<%= render "forms" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <%= render "components/navbar"%>

  <%= yield %>

  <%= render "components/footer"%>
  </body>
</html>

app/views/lists/_forms.html.erb
<%= render "components/banner", text: "", title: "Add your new list" %>

<div class="container">

  <div class="d-flex justify-content-center mt-5 ">
    <%= simple_form_for @list do |f| %>
      <%= f.input :name %>
      <%=  f.button :submit, class: "btn btn-lg mt-5 backgradient" %>
    <% end %>
  </div>
</div>

app/views/lists/index.html.erb
<%= render "components/banner", text: "Save any kind of movies", title: "Lister" %>

<div class="container">
  <div class="cards mt-4">
    <% @lists.each do |list|%>
      <%= link_to(list_path(list.id), class: "text-decoration-none" ) do %>
        <div class="card-category backgradient mb-5" >
          <%= list.name %>
        </div>
      <% end %>
    <% end%>

  </div>
</div>

app/views/lists/new.html.erb
<%= render "forms"%>

app/views/lists/show.html.erb
<%= render "components/banner", text:  @list.bookmarks.length == 1 ? "#{@list.bookmarks.length} Movie" : "#{@list.bookmarks.length} Movies"   , title: "#{@list.name}" %>

<div class="container">

  <%= link_to(new_list_bookmark_path(@list)) do %>
  <button type="button" class="btn backgradient btn-lg text-white mt-5" >Add a movie</button>
  <% end %>



  <div class="cards mt-5">
     <% @list.bookmarks.each do |bookmark| %>
      <%= render "components/bookmarkcard", url: bookmark.movie.poster_url , moviename:bookmark.movie.title, rating:bookmark.movie.rating, overview:truncate(bookmark.movie.overview, :length => 90), comment:bookmark.comment, id: bookmark.id %>
     <% end %>
  </div>

  <div class="d-flex mb-5">
        <div  style="width:50%;flex-grow:1" >
          <h1> Reviews </h1>

          <% if @list.reviews.empty?  %>
            <h2 class="text-muted mt-5"> There's no comments yet..</h2>
          <% else %>
          <% @list.reviews.first(2).each do |review| %>
           <div class="d-flex justify-content-center">
                <div class="card-body p-4">
                  <div class="card shadow rounded border-0 mb-4 bg-white">
                    <div class="card-body">
                      <p><%= review.content %></p>
                        <div class="d-flex justify-content-between">
                          <div class="d-flex flex-row align-items-center">
                             <%= "⭐" * review.stars %>

                          </div>
                          <div class="text-muted fs-6 text fst-italic">
                          1 min ago
                          </div>
                        </div>
                    </div>
                  </div>
                </div>
                </div>
                <% end %>
                <% end %>



        </div>

    <div  style="width:50%;flex-grow:1">

    <div class="d-flex justify-content-center">

        <div class="card shadow rounded border-0 bg-white">
          <div class="card-body p-4">
            <div class="d-flex flex-start w-100">
              <div class="w-100">
                <h5>Add a comment</h5>
                <%= simple_form_for [@list, @review] do |f| %>
                <ul class="list-group list-group-horizontal ">
                      <% i= 1%>
                      <%= f.collection_radio_buttons :stars, [[1], [2], [3], [4], [5]], :first, :last, item_wrapper_tag: false, boolean_style: :inline do |b| %>
                        <li class="list-group-item bg-white border-0 "> <%= b.radio_button + b.label {"#{i} ⭐"} %> </li>
                        <% i= i +1%>
                      <% end %>

                       </ul>
                    <div class="form-outline mt-2">
                      <%= f.input :content %>
                      <label class="form-label" for="textAreaExample">What is your view?</label>
                    </div>
                    <div class="d-flex justify-content-between mt-3">
                      <%= f.submit "Create a Review", class: "btn backgradient text-white" %>
                    </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>


    </div>
  </div>

</div>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>